### ISSUE TITLE
Request: Crop right click compatibility for Plant Mega Pack and Witchery

### ISSUE THREAD

**Issue by BBoldt** [tterrag1098/ttCore#21]
My config file: http://hastebin.com/ibapivayeb.hs

Plant Mega Pack: http://minecraft.curseforge.com/mc-mods/70748-plant-mega-pack

Witchery: http://minecraft.curseforge.com/mc-mods/69673-witchery

They all act like regular crops in-game, so I'm not sure why your right click system isn't working for them. The only "weird" ones are the water-based plants in plant mega pack, the water based plant in witchery, and the mandrake plant. Also, I guess the 2 block tall ones are incompatible, as you said in IRC.

Also, I don't know if it's worth looking into, but only 4 of the Pneumaticraft crops work with your system. Plastic plants do weird crazy stuff by default though, so I wasn't really expecting them to work in the first place. The 4 that do work are Burst, Chopper, Propulsion, and Flying.

**Comment by BBoldt** [comment]
Okay I'm noticing a pattern, most of the Plant Mega Pack and Witchery crops become mature at meta data :4, and I think that's confusing the right clicky thing in ttcore somehow.

The one witchery crop that works is wolfsbane, and it's 'mature' meta data is :7.

**Comment by tterrag1098** [comment]
That would be why the config provides you the option to change the max meta for the crop, which was the whole reason I implemented it in the first place.

`"meta":4`

That would do the trick.

**Comment by BBoldt** [comment]
I didn't know that was a thing.
That seems to have fixed most things, but there are still a few that don't work, the tomato crop for instance. It's max meta is 4, and yet it still won't harvest on right click. It's not a 2 block tall one either.

I'll have to screw around with the Pneumaticraft ones a bit more tomorrow, they use meta data really strangely. 

Updated config: http://hastebin.com/muzupudixo.hs
